-- Group chat reliability: call tables, member mentions, gallery avatars, and everyone-editable group info.
create table if not exists public.group_calls (
  id uuid primary key default gen_random_uuid(), group_id uuid not null references public.groups(id) on delete cascade,
  started_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  kind text not null default 'audio' check (kind in ('audio','video')), status text not null default 'ringing' check (status in ('ringing','active','ended')),
  started_at timestamptz not null default now(), ended_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.group_call_participants (call_id uuid not null references public.group_calls(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, joined_at timestamptz not null default now(), left_at timestamptz, primary key (call_id, user_id));
create index if not exists group_calls_group_idx on public.group_calls(group_id, created_at desc);
create table if not exists public.group_message_mentions (message_id uuid not null references public.group_messages(id) on delete cascade, group_id uuid not null references public.groups(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key (message_id, user_id));
create index if not exists group_message_mentions_user_idx on public.group_message_mentions(user_id, created_at desc);
alter table public.group_permissions alter column edit_info set default 'everyone';
update public.group_permissions set edit_info = 'everyone' where edit_info = 'admins';
do $$ begin if exists (select 1 from pg_constraint where conname = 'notifications_type_check' and conrelid = 'public.notifications'::regclass) then alter table public.notifications drop constraint notifications_type_check; end if; alter table public.notifications add constraint notifications_type_check check (type in ('like','comment','follow','follow_request','follow_accepted','verified','broadcast','suspended','story_like','story_reply','reel_like','reel_comment','comment_reply','message','new_story','new_post','new_reel','new_video','group_mention')); end $$;
grant select, insert, update, delete on public.group_calls to authenticated; grant select, insert, update, delete on public.group_call_participants to authenticated; grant select, insert on public.group_message_mentions to authenticated;
alter table public.group_calls enable row level security; alter table public.group_call_participants enable row level security; alter table public.group_message_mentions enable row level security;
drop policy if exists "members read calls" on public.group_calls; create policy "members read calls" on public.group_calls for select to authenticated using (public.is_group_member(group_id));
drop policy if exists "allowed members start calls" on public.group_calls; create policy "allowed members start calls" on public.group_calls for insert to authenticated with check (started_by = auth.uid() and public.group_can(group_id, 'start_calls'));
drop policy if exists "members update calls" on public.group_calls; create policy "members update calls" on public.group_calls for update to authenticated using (public.is_group_member(group_id)) with check (public.is_group_member(group_id));
drop policy if exists "members read call participants" on public.group_call_participants; create policy "members read call participants" on public.group_call_participants for select to authenticated using (exists (select 1 from public.group_calls c where c.id = call_id and public.is_group_member(c.group_id)));
drop policy if exists "members join call" on public.group_call_participants; create policy "members join call" on public.group_call_participants for insert to authenticated with check (user_id = auth.uid() and exists (select 1 from public.group_calls c where c.id = call_id and public.is_group_member(c.group_id)));
drop policy if exists "members update own call row" on public.group_call_participants; create policy "members update own call row" on public.group_call_participants for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "members read mentions" on public.group_message_mentions; create policy "members read mentions" on public.group_message_mentions for select to authenticated using (public.is_group_member(group_id));
drop policy if exists "senders create mentions" on public.group_message_mentions; create policy "senders create mentions" on public.group_message_mentions for insert to authenticated with check (exists (select 1 from public.group_messages m where m.id = message_id and m.sender_id = auth.uid() and m.group_id = group_id));
do $$ begin begin alter publication supabase_realtime add table public.group_calls; exception when duplicate_object then null; end; begin alter publication supabase_realtime add table public.group_call_participants; exception when duplicate_object then null; end; begin alter publication supabase_realtime add table public.group_message_mentions; exception when duplicate_object then null; end; end $$;